name: Test

on:
  push:
  pull_request:

env:
  JAVA_DIST: 'zulu'
  JAVA_VERSION: 22

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Compile and Test with different JVM Flags
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jvm_flag:
          - "-XX:+UseG1GC"
          - "-XX:+HeapDumpOnOutOfMemoryError"
          - "-XX:-AllowUserSignalHandlers"
          - "-XX:+EliminateLocks"
          - "-XX:+TieredCompilation"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DIST }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
      - name: Build and Test with JVM Flag
        run: |
          echo "Running tests with flag: ${{ matrix.jvm_flag }}"
          xvfb-run mvn -B verify -Djavafx.platform=linux -DargLine="${{ matrix.jvm_flag }}" jacoco:report -Pcoverage
          unset MAVEN_OPTS

      - name: Get JaCoCo Coverage
        id: coverage
        run: |
          echo "Extracting coverage for flag: ${{ matrix.jvm_flag }}"
          coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv) 
          echo "Coverage for flag ${{ matrix.jvm_flag }}: $coverage%"
          echo "COVERAGE=$coverage" >> $GITHUB_ENV

      - name: Fail if coverage has not improved.
        run: |
          coverage=$COVERAGE
          threshold=13.43
          if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then
            echo "Coverage has not improved with flag ${{ matrix.flag }}."
            exit 1
          else
            echo "New coverage with flag ${{ matrix.flag }}: $coverage%"
          fi
      - name: Réponse
        run: echo "Parce qu'il y a trop de bugs🐛!!"